# Generated by Django 6.1 on 2026-09-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationMapping",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "fc_code",
                    models.CharField(
                        max_length=10, verbose_name="รหัสสถานที่ (FC code)"
                    ),
                ),
                ("name_th", models.TextField(verbose_name="ชื่อสถานที่")),
                (
                    "group",
                    models.CharField(
                        db_column="group", max_length=50, verbose_name="กลุ่มพื้นที่"
                    ),
                ),
                (
                    "sub_location",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="จุดส่งย่อย"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "จุดส่ง",
                "verbose_name_plural": "Location Mapping",
                "db_table": "location_mapping",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LogisticGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=50, verbose_name="ชื่อกลุ่มพื้นที่"),
                ),
                (
                    "template_key",
                    models.CharField(
                        max_length=50,
                        verbose_name="Template key (ต้องขึ้นต้นด้วย logistic_)",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(
                        max_length=100, verbose_name="ชื่อ Sheet ในไฟล์เทมเพลต"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="ลำดับแสดงผล"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "กลุ่มพื้นที่ (Logistic)",
                "verbose_name_plural": "กลุ่มพื้นที่ (Logistic)",
                "db_table": "logistic_group",
                "ordering": ["display_order", "group_name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("output_dir", models.TextField()),
                ("production_plan_path", models.TextField(blank=True, null=True)),
                (
                    "production_plan_status",
                    models.CharField(default="success", max_length=20),
                ),
                ("production_plan_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Plan Run",
                "verbose_name_plural": "Plan Runs",
                "db_table": "plan_run",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlanRunImport",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "plan_run_id",
                        "po_import_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "db_table": "plan_run_import",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlanRunLogisticFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("file_path", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Logistic File",
                "verbose_name_plural": "Logistic Files",
                "db_table": "plan_run_logistic_file",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PlanSkuResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sheet_type", models.CharField(max_length=20)),
                ("group_name", models.CharField(blank=True, max_length=50, null=True)),
                ("barcode", models.CharField(max_length=20)),
                ("name_th", models.TextField(blank=True, null=True)),
                ("name_en", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pack_size", models.IntegerField(blank=True, null=True)),
                ("column_label", models.CharField(max_length=100)),
                (
                    "qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pack_text", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "grand_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "buffer_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "return_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_production_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("basket_total", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ผลคำนวณแผน (ต่อรหัสสินค้า)",
                "verbose_name_plural": "ผลคำนวณแผน (ต่อรหัสสินค้า)",
                "db_table": "plan_sku_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_filename", models.TextField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "production_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่ผลิต"),
                ),
                (
                    "po_date",
                    models.DateField(blank=True, null=True, verbose_name="วันที่ PO"),
                ),
                ("total_rows", models.IntegerField(blank=True, null=True)),
                ("status", models.CharField(default="imported", max_length=20)),
                ("column_order", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PO Import",
                "verbose_name_plural": "PO Imports",
                "db_table": "po_import",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PoLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=30)),
                ("po_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "delivery_time",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("fc_code", models.CharField(max_length=10)),
                ("delivery_location", models.TextField(blank=True, null=True)),
                ("line_no", models.IntegerField(blank=True, null=True)),
                ("barcode", models.CharField(max_length=20)),
                ("item_name", models.TextField(blank=True, null=True)),
                ("qty_ordered", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_type", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "net_case_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("all_values", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "PO Line",
                "verbose_name_plural": "PO Lines",
                "db_table": "po_line",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductMaster",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("barcode", models.CharField(max_length=20, verbose_name="บาร์โค้ด")),
                ("name_th", models.TextField(verbose_name="ชื่อสินค้า (ไทย)")),
                (
                    "name_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="ชื่อสินค้า (อังกฤษ)"
                    ),
                ),
                (
                    "pack_size",
                    models.IntegerField(verbose_name="บรรจุ/ตก. (ชิ้นต่อตะกร้า)"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="ราคา",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, null=True, verbose_name="หมายเหตุ"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="เปิดใช้งาน"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "รหัสสินค้า",
                "verbose_name_plural": "รหัสสินค้า (Product Code)",
                "db_table": "product_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_key", models.CharField(max_length=50)),
                ("version_number", models.IntegerField()),
                ("file_path", models.TextField()),
                ("original_filename", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("validation_summary", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Template Version",
                "verbose_name_plural": "Template Versions",
                "db_table": "template_version",
                "ordering": ["-version_number"],
                "managed": False,
            },
        ),
    ]
