# Generated by Django 6.1 on 2026-09-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpall", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateMappingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapping_rules",
                    models.JSONField(
                        default=dict,
                        help_text="กฎการค้นหาและ Mapping คอลัมน์ (เช่น หาคำว่า 'ขอนแก่น' ในแถวที่ 5)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template Mapping Config",
                "db_table": "template_mapping_config",
                "managed": False,
            },
        ),
    ]
